version: '3.8'

services:
  tiago_base:
    extends:
      file: .compose_templates.yml
      service: .tiago_sim
    command:
      - bash
      - -c
      - |
        ros2 launch rwu_tiago_bringup sim_robocup_2023.launch.py is_public_sim:=True x:=-4.15 y:=2.26 yaw:=1.61 navigation:=True slam:=False map_path:=/maps/myfirstmap.yaml &&
        tail -f /dev/null

  apriltag_detection:
    container_name: my_ros2_apriltag_detection
    extends:
      file: ../submodules/ros-2-apriltags/docker/docker-compose.yml
      service: apriltag_detection
    command:
      - bash
      - -c
      - |
        ros2 run apriltag_ros apriltag_node --ros-args -r image_rect:=/head_front_camera/rgb/image_raw -r camera_info:=/head_front_camera/rgb/camera_info --params-file `ros2 pkg prefix apriltag_ros`/share/apriltag_ros/cfg/tags_36h11.yaml

  tiago_workspace_container:
    extends:
      file: .compose_templates.yml
      service: .tiago_workspace
    image: my_tiago_workspace
    build:
      dockerfile: docker/Dockerfile_workspace
    depends_on:
      - tiago_base
      - apriltag_detection
    command:
      - bash
      - -c
      - |
        sleep 80
        cd /root/ros2_ws/src/nb-246830/models && python3 spawn_objects_single.py && 
        tail -f /dev/null


  tiago_workspace_conainer:
    extends:
      file: .compose_templates.yml
      service: .tiago_workspace
    image: my_tiago_workspace
    build:
      dockerfile: docker/Dockerfile_workspace
    command: 
      - bash
      - -c
      - |
        sleep 70
        ros2 action send_goal /head_controller/increment teleop_tools_msgs/action/Increment "{increment_by:[0.0,-0.8,0.1]}" &&
        sleep 50
        ros2 run add_collision_object add_collision_object_srv &&
        tail -f /dev/null